import getpass
print("\tGGITS CANTEEN SYSTEM\t")
print("\t CANTEEN MENU \t")
print("s.no\t\titem\t\tprice")
print("101\tsamosa    \t\tRs10")
print("102\tveg puff\t\tRs35")
print("103\tcheese puff\t\tRs50")
print("104\tlays    \t\tRs20")
print("105\tkurure    \t\tRs10")
print("106\tbiscuits\t\tRs10")
print("107\tsambhar vada\t\tRs15")
print("108\tonion paratha\t\tRs15")
print("109\taloo paratha\t\tRs15")
print("110\tpaneer biryani\t\tRs30")
print("111\tpaneer fried rice\tRs30")
print("112\tveg cutlet\t\tRs15")
print("113\tplain maggie\t\tRs20")
print("114\tcheese maggie\t\tRs30")
print("115\tmasala maggie\t\tRs30")
print("116\tmasala dosa\t\tRs30")
print("117\tmilk    \t\tRs10")
print("118\tcofeee    \t\tRs10")
print("119\ttea        \t\tRs10")
print("120\tcold drinks\t\tRs20")
print("150\texit\t\t")

name=input("enter your name: ")
password=getpass.getpass("enter password: ")
while password!="welcome":
    print("incorrect input...please try again!!!")
    password=getpass.getpass("enter password: ")
choice=int(input("enter choice"))


